// AgriHelper - Data Store

const CropData = [
    {
        id: 'wheat',
        name: 'Wheat',
        icon: '🌾',
        category: 'Cereal',
        description: 'Wheat is one of the world\'s most important staple crops grown in cool seasons.',
        scientificName: 'Triticum aestivum',
        cropType: 'Cereal',
        season: 'Rabi (Winter)',
        duration: '100-150 days',
        soil: 'Loamy soil',
        pH: '6.0-7.5',
        temperature: '10-25°C',
        rainfall: '50-100 cm',
        nitrogen: '120 kg/hectare',
        phosphorus: '60 kg/hectare',
        potassium: '40 kg/hectare',
        organicAlternatives: 'Farmyard manure (FYM) 10-15 tonnes/hectare, Vermicompost 5 tonnes/hectare, Green manure',
        irrigationFrequency: 'Every 20-25 days, 4-6 irrigations required',
        criticalStages: 'Crown Root Initiation (CRI), Tillering, Flowering, Grain filling',
        yieldPerAcre: '18-25 quintals per acre',
        marketPrice: '₹2,000-2,500 per quintal',
        estimatedProfit: '₹25,000-40,000 per acre',
        diseases: [
            { name: 'Rust (Leaf, Stem, Stripe)', symptoms: 'Orange-brown pustules on leaves and stems', treatment: 'Spray Propiconazole or Tebuconazole fungicides' },
            { name: 'Powdery Mildew', symptoms: 'White powdery coating on leaves', treatment: 'Apply Sulfur-based fungicides' },
            { name: 'Karnal Bunt', symptoms: 'Black powdery mass in grains', treatment: 'Seed treatment with Tebuconazole' }
        ],
        schemes: ['Kisan Credit Card (KCC)', 'PM Fasal Bima Yojana (PMFBY)', 'Minimum Support Price (MSP) scheme'],
        insurance: 'Covered under PMFBY - Premium 1.5% of sum insured'
    },
    {
        id: 'maize',
        name: 'Maize',
        icon: '🌽',
        category: 'Cereal',
        description: 'Maize is a versatile crop used for food, feed, and industrial products.',
        scientificName: 'Zea mays',
        cropType: 'Cereal',
        season: 'Kharif & Rabi',
        duration: '80-110 days',
        soil: 'Well-drained loamy soil',
        pH: '5.5-7.0',
        temperature: '18-27°C',
        rainfall: '60-120 cm',
        nitrogen: '150 kg/hectare',
        phosphorus: '75 kg/hectare',
        potassium: '40 kg/hectare',
        organicAlternatives: 'Compost 8-10 tonnes/hectare, Poultry manure 3-4 tonnes/hectare, Bio-fertilizers',
        irrigationFrequency: 'Every 10-15 days, 6-8 irrigations required',
        criticalStages: 'Knee-high stage, Tasseling, Silking, Grain filling',
        yieldPerAcre: '20-30 quintals per acre',
        marketPrice: '₹1,800-2,200 per quintal',
        estimatedProfit: '₹30,000-50,000 per acre',
        diseases: [
            { name: 'Leaf Blight', symptoms: 'Long grayish lesions on leaves', treatment: 'Spray Mancozeb or Carbendazim' },
            { name: 'Maize Dwarf Mosaic', symptoms: 'Stunted growth, yellow streaks', treatment: 'Control aphids, use resistant varieties' },
            { name: 'Stalk Rot', symptoms: 'Rotting of lower stem', treatment: 'Improve drainage, balanced fertilization' }
        ],
        schemes: ['Kisan Credit Card (KCC)', 'PM Fasal Bima Yojana (PMFBY)', 'National Food Security Mission'],
        insurance: 'Covered under PMFBY - Premium 2% of sum insured'
    },
    {
        id: 'tomato',
        name: 'Tomato',
        icon: '🍅',
        category: 'Vegetable',
        description: 'Tomatoes are widely cultivated and used in various cuisines worldwide.',
        scientificName: 'Solanum lycopersicum',
        cropType: 'Vegetable',
        season: 'Year-round (with protection)',
        duration: '60-90 days',
        soil: 'Sandy loam',
        pH: '6.0-7.0',
        temperature: '20-30°C',
        rainfall: 'Moderate (60-150 cm)',
        nitrogen: '100 kg/hectare',
        phosphorus: '50 kg/hectare',
        potassium: '50 kg/hectare',
        organicAlternatives: 'FYM 25 tonnes/hectare, Neem cake 500 kg/hectare, Vermicompost 3-5 tonnes/hectare',
        irrigationFrequency: 'Every 3-5 days in summer, 7-10 days in winter',
        criticalStages: 'Transplanting, Flowering, Fruit development',
        yieldPerAcre: '200-300 quintals per acre',
        marketPrice: '₹10-40 per kg (highly seasonal)',
        estimatedProfit: '₹80,000-1,50,000 per acre',
        diseases: [
            { name: 'Early Blight', symptoms: 'Dark brown spots with concentric rings', treatment: 'Spray Mancozeb or Chlorothalonil' },
            { name: 'Late Blight', symptoms: 'Water-soaked lesions on leaves and fruits', treatment: 'Apply Metalaxyl + Mancozeb' },
            { name: 'Bacterial Wilt', symptoms: 'Sudden wilting of entire plant', treatment: 'Remove infected plants, crop rotation' }
        ],
        schemes: ['PM Kisan Samman Nidhi', 'Horticulture Mission', 'Vegetable Cluster Development'],
        insurance: 'Covered under PMFBY and specialized horticulture insurance'
    },
    {
        id: 'soybean',
        name: 'Soybean',
        icon: '🌱',
        category: 'Pulse',
        description: 'Soybean is a high-protein crop used for oil and animal feed.',
        scientificName: 'Glycine max',
        cropType: 'Pulse/Oilseed',
        season: 'Kharif',
        duration: '85-120 days',
        soil: 'Well-drained black soil',
        pH: '6.0-7.5',
        temperature: '20-30°C',
        rainfall: '60-100 cm',
        nitrogen: '30 kg/hectare',
        phosphorus: '80 kg/hectare',
        potassium: '40 kg/hectare',
        organicAlternatives: 'Rhizobium culture (seed treatment), FYM 5-6 tonnes/hectare, Rock phosphate',
        irrigationFrequency: 'Every 15-20 days, 3-4 irrigations required',
        criticalStages: 'Flowering, Pod formation, Pod filling',
        yieldPerAcre: '8-12 quintals per acre',
        marketPrice: '₹3,500-4,500 per quintal',
        estimatedProfit: '₹20,000-35,000 per acre',
        diseases: [
            { name: 'Yellow Mosaic Virus', symptoms: 'Yellow mottling on leaves', treatment: 'Control whiteflies, use resistant varieties' },
            { name: 'Rust', symptoms: 'Reddish-brown pustules on leaves', treatment: 'Spray Hexaconazole or Tebuconazole' },
            { name: 'Charcoal Rot', symptoms: 'Black discoloration of stem base', treatment: 'Seed treatment, avoid water stress' }
        ],
        schemes: ['National Food Security Mission (Pulses)', 'Oilseeds Production Programme', 'KCC'],
        insurance: 'Covered under PMFBY - Premium 2% of sum insured'
    },
    {
        id: 'sugarcane',
        name: 'Sugarcane',
        icon: '🎋',
        category: 'Cash Crop',
        description: 'Sugarcane is a tropical crop used for sugar and ethanol production.',
        scientificName: 'Saccharum officinarum',
        cropType: 'Cash Crop',
        season: 'Year-round',
        duration: '10-18 months',
        soil: 'Deep fertile loamy soil',
        pH: '6.5-7.5',
        temperature: '20-35°C',
        rainfall: '100-150 cm',
        nitrogen: '250 kg/hectare',
        phosphorus: '115 kg/hectare',
        potassium: '115 kg/hectare',
        organicAlternatives: 'Press mud 10 tonnes/hectare, FYM 15-20 tonnes/hectare, Green manure',
        irrigationFrequency: 'Every 7-15 days depending on stage, 30-35 irrigations',
        criticalStages: 'Germination, Tillering, Grand growth phase',
        yieldPerAcre: '30-40 tons per acre',
        marketPrice: '₹300-350 per quintal (FRP)',
        estimatedProfit: '₹50,000-80,000 per acre',
        diseases: [
            { name: 'Red Rot', symptoms: 'Reddening of internal tissues', treatment: 'Use resistant varieties, hot water treatment of setts' },
            { name: 'Smut', symptoms: 'Whip-like structure from shoot', treatment: 'Remove infected shoots, use disease-free setts' },
            { name: 'Wilt', symptoms: 'Yellowing and drying of leaves', treatment: 'Improve drainage, use healthy planting material' }
        ],
        schemes: ['Sugarcane Development Schemes', 'Fair and Remunerative Price (FRP)', 'KCC for Sugarcane'],
        insurance: 'Covered under PMFBY and state-specific sugarcane insurance schemes'
    }
];

const LoanData = [
    {
        name: 'Kisan Credit Card Scheme',
        shortName: 'KCC',
        type: 'Crop Loan',
        region: 'National',
        description: 'Provides affordable credit to farmers for crop production and allied activities.',
        interest: '4%',
        maxAmount: '₹3,00,000',
        benefits: ['Low interest rate', 'Flexible repayment']
    },
    {
        name: 'PM Fasal Bima Yojana',
        shortName: 'PMFBY',
        type: 'Subsidy',
        region: 'State',
        description: 'Crop insurance scheme providing financial support to farmers in case of crop loss.',
        interest: '2%',
        maxAmount: '₹2,00,000',
        benefits: ['Insurance coverage', 'Risk protection']
    },
    {
        name: 'PM-KISAN Scheme',
        shortName: 'PM-KISAN',
        type: 'Subsidy',
        region: 'National',
        description: 'Direct income support of ₹6,000 per year to all farmer families.',
        interest: '0%',
        maxAmount: '₹6,000/year',
        benefits: ['Direct bank transfer', 'Three installments']
    },
    {
        name: 'Agricultural Term Loan',
        shortName: 'ATL',
        type: 'Crop Loan',
        region: 'State',
        description: 'Long-term loans for farm equipment, irrigation, and land development.',
        interest: '7%',
        maxAmount: '₹10,00,000',
        benefits: ['Long repayment period', 'Equipment financing']
    }
];
